# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-aurora-postgres
  description: This component is responsible for provisioning Aurora Postgres RDS clusters
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




